import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Parkinsans, Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Toaster } from "sonner";
import { AppProvider } from "@/context/AppContext";
import ReCaptchaProvider from "@/components/ReCaptcha/ReCaptchaProvider";
import { CookieConsentProvider } from "@/components/cookie-consent/cookie-context";
import { CookieBanner } from "@/components/cookie-consent/cookie-banner";

const parkinsans = Parkinsans({
  variable: "--font-parkinsans",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});
const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus_Jakarta_Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo1.ico", // path from public folder
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} ${parkinsans.variable} ${orbitron.variable} font-parkinsans antialiased`}
      >
        <ReCaptchaProvider>
          <CookieConsentProvider>
          <AppProvider>
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </AppProvider>
          <CookieBanner/>
          </CookieConsentProvider>
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
