import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Parkinsans, Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";


const parkinsans = Parkinsans({
  variable: "--font-parkinsans",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});
const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus_Jakarta_Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} ${parkinsans.variable} ${orbitron.variable} font-parkinsans antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
